export const ADD_CUBE = 'ADD_CUBE'
export const SHUFFLE = 'SHUFFLE'
export const CHANGE_ODD = 'CHANGE_ODD'
export const STOP_ODD = 'STOP_ODD'
export const RESET = 'RESET'
export const EASTER_EGG = 'EASTER_EGG'